name: Verify Email
on: 
  workflow_dispatch:
    inputs:
      to:
        description: 'recipient(s)'
        required: false
      # revision:
      #   description: 'Revision of release'
      #   required: true
jobs:
  email:
    name: Prepare email
    runs-on: "ubuntu-24.04"
    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: Send email
        uses: dawidd6/action-send-mail@v4
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          # Required mail server port:
          server_port: 587
          # Optional (recommended): mail server username:
          username: ${{secrets.muser}}
          # Optional (recommended) mail server password:
          password: ${{secrets.mpass}}
          # Required mail subject:
          subject: Verify your email address
          # Required recipients' addresses:
          to: ${{ inputs.to }}, lee.calcote@layer5.io
          # Required sender full name (address can be skipped):
          from: "Meshery Cloud" # <user@example.com>
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: false
          # Optional plain body:
          body: Verify your email. Follow the link below.
          # Optional carbon copy recipients:
          # cc: leecalcote@icloud.com
          # Optional blind carbon copy  recipients:
          # bcc: r2d2@example.com,hansolo@example.com
          # Optional recipient of the email response:
          reply_to: noreply@layer5.io
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: false
          # Optional attachments:
          # attachments: attachments.zip,git.diff,./dist/static/*.js
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: normal
          # Optional HTML body read from file:
          html_body: '<html>
<style>
    body {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        font-family: "Qanelas Soft,Arial"; 
    }
    @font-face {
        font-family: "Qanelas Soft";
         src: url("http://db.onlinewebfonts.com/t/5173256ffa3e08c4cbed8986369258a6.eot"); /* IE9*/
        src: url("http://db.onlinewebfonts.com/t/5173256ffa3e08c4cbed8986369258a6.eot?#iefix") format("embedded-opentype"), /* IE6-IE8 */
        url("http://db.onlinewebfonts.com/t/5173256ffa3e08c4cbed8986369258a6.woff2") format("woff2"), /* chrome firefox */
        url("http://db.onlinewebfonts.com/t/5173256ffa3e08c4cbed8986369258a6.woff") format("woff"), /* chrome firefox */
        url("http://db.onlinewebfonts.com/t/5173256ffa3e08c4cbed8986369258a6.ttf") format("truetype"), /* chrome firefox opera Safari, Android, iOS 4.2+*/
        url("http://db.onlinewebfonts.com/t/5173256ffa3e08c4cbed8986369258a6.svg#Qanelas Soft") format("svg"); /* iOS 4.1- */
    }
    p { font-family: "Qanelas Soft,Arial";        
        padding: 1rem;
        margin: 1rem;
        font-size: 1.1rem;
    }
    a { color: #00B39F; }
    a:visited { color: #00B39F; }
    .verify {
        display: flex;
        flex-direction: column;
        border-radius: .5rem;
        color: #1e2117;
        border: #7A848E 1px solid;
        font-family: "Qanelas Soft,Arial";
        align-content: center;
        margin: 1.5rem;
        
    }
    .header {
        display: flex;
        background-color: #1e2117;
        padding: 1rem;
        margin: 0rem;
        justify-content: center;
        align-items: flex-start;
    }
    .header-logo {
        width: 350px;
    }
    .button {
        padding: 1rem;
        margin: 1 4rem;
        font-size: 1.1rem;
        background-color: #00B39F;
        border: none;
        cursor: pointer;
        color: white;
        border-radius: .5rem;
    }
    .button:hover {
        background-color: #00D3A9;
    }
    .contact {
        display: flex;
        justify-content: center;
        font-size: 1rem;
        margin-top: 1.5rem;
    }
    .footer {
        background-color: #1e2117;
        display: flex;
        position: relative;
        flex-direction: row;
        justify-content: center;
        align-items: center;
        padding: 1rem;
        height: 2.25rem;
    } 
    .social {
        height: 1.25rem;
        width: 1.25rem;
        padding: 0 .75rem;
        align-self: center;
    }
    .copyright { 
        margin-top:.75rem; font-size: .9rem; color: #7A848E;   
        font-style: italic; 
        display: flex;
        justify-content: center;
    }
    </style>
    <body>
        <div class="header">
            <img class="header-logo"
                src="https://raw.githubusercontent.com/layer5labs/meshery-extensions-packages/master/email/layer5-cloud/meshery-cloud.svg"
                alt="Meshery logo" />
        </div>
        <div class="verify">
            <p>Hi,<br /><br />
                Click below to verify your email address and enable your Meshery Cloud account.
            </p>
            <button class="button">Verify email address</button>
            <p class="contact">Need any help?&nbsp;<a href="https://discuss.layer5.io">Contact us</a>.</p>
        </div>
        <div class="footer">
                <a href="https://twitter.com/layer5">
                    <img class="social" src="https://mcusercontent.com/6b50be5aea3dfe1fd4c041d80/images/7547690c-0a33-4f92-985a-d8109765db24.png"></a>
                <a href="https://www.linkedin.com/company/layer5">
                    <img class="social" src="https://mcusercontent.com/6b50be5aea3dfe1fd4c041d80/images/c3115a39-5f32-43a7-92d4-e0a14b3a626d.png"></a>
                <a href="https://slack.layer5.io">
                    <img class="social" src="https://mcusercontent.com/6b50be5aea3dfe1fd4c041d80/images/7d98d789-47d6-4fe0-8074-f65de989eb08.png"></a>
                <a href="https://www.youtube.com/c/Layer5io">
                    <img class="social" src="https://mcusercontent.com/6b50be5aea3dfe1fd4c041d80/images/1cce1b1a-c045-40cd-9a49-39ac5f193516.png" style="width:1.5rem;"></a>
        </div>    
        <p class="copyright">Copyright 2022, Layer5, Inc. All right reserved.</p>
    </body>
    </html>'
